---
- name: install lamp
  become: yes
  hosts: all
  vars:
    - php_page_location: /var/www/html/info.php
  tasks:
    - name: to update
      ansible.builtin.apt:
        update_cache: yes
    - name: install apache
      ansible.builtin.package:
        name: apache2
        state: present
      notify:
        - ensure apache in enabled and restarted
    - name: to install packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - php
        - libapache2-mod-php
      notify:
        - ensure apache in enabled and restarted
    - name: copy php page
      ansible.builtin.copy:
        src: www/info.php
        dest: "{{ php_page_location }}"
      notify:
        - ensure apache in enabled and restarted
    - name: ensure apache in enabled and restarted
      ansible.builtin.service:
        name: apache2
        enabled: yes
        state: restarted