---
- name: install lamp
  become: yes
  hosts: webserver
  tasks:
    - name: to update
      ansible.builtin.apt:
        update_cache: yes
    - name: install apache
      ansible.builtin.package:
        name: "{{ package_name }}"
        state: present
      notify:
        - ensure apache in enabled and restarted
    - name: to install packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: "{{ php_packages }}"
      notify:
        - ensure apache in enabled and restarted
    - name: copy php page
      ansible.builtin.copy:
        src: www/info.php
        dest: "{{ php_page_location }}"
      notify:
        - ensure apache in enabled and restarted
  handlers:
    - name: ensure apache in enabled and restarted
      ansible.builtin.service:
        name: "{{ package_name }}"
        enabled: yes
        state: restarted