---
- name: install lamp
  become: yes
  hosts: all
  packages:
    - php
    - libapache2-mod-php
    - php-mysql
  tasks:
    - name: to update
      ansible.builtin.apt:
        update_cache: yes
    - name: install apache
      ansible.builtin.package:
        name: apache2
        state: present
    - name: to install packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"
