---
- name: installing tomcat
  become: yes
  hosts: all
  vars:
    - home_dir: /opt/tomcat
    - user_name: tomcat
    - default_shell: /bin/false
  tasks:
    - name: install java
      ansible.builtin.apt:
        update_cache: yes
        name: openjdk-11-jdk
        state: present
      when: ansible_facts['os_family']=="Debian"
    - name: create a system user
      ansible.builtin.user:
        create_home: yes
        name: "{{ user_name }}"
        home: "{{ home_dir }}"
        shell: "{{ default_shell }}"
        state: present
      when: ansible_facts['os_family']=="Debian"
