---
- name: installing tomcat
  become: yes
  hosts: all
  tasks:
    - name: install java
      ansible.builtin.apt:
        update_cache: yes
        name: openjdk-11-jdk
        state: present
    - name: create a system user
      ansible.builtin.user:
        create_home: yes
        group: tomcat
        name: tomcat
        home: /opt/tomcat
        shell: /bin/false
        state: present
