---
- name: installing tomcat
  become: yes
  hosts: all
  vars:
    - home_dir: /opt/tomcat
    - user_name: tomcat
    - default_shell: /bin/false
    - tomcat_version: 9.0.70
    - tomcat_latest: /opt/tomcat/latest
  tasks:
    - name: update cache
      apt:
        update_cache: yes
      when: ansible_facts['os_family']=="Debian"
    - name: install java
      ansible.builtin.apt:
        update_cache: yes
        name: openjdk-11-jdk
        state: present
      when: ansible_facts['os_family']=="Debian"
    - name: create a system user
      ansible.builtin.user:
        create_home: yes
        name: "{{ user_name }}"
        home: "{{ home_dir }}"
        shell: "{{ default_shell }}"
        state: present
      when: ansible_facts['os_family']=="Debian"
    - name: download tomcat
      ansible.builtin.get_url:
        url: "https://www-eu.apache.org/dist/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
      when: ansible_facts['os_family']=="Debian"
    - name: extract zip files
      ansible.builtin.unarchive:
        creates: "{{ home_dir }}/apache-tomcat-{{ tomcat_version }}"
        src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "{{ home_dir }}/apache-tomcat-{{ tomcat_version }}"
        remote_src: true
        group: "{{ user_name }}"
        user: "{{ user_name }}"
      when: ansible_facts['os_family']=="Debian"
    - name: create sym link
      ansible.builtin.file:
        src: "{{ home_dir }}/apache-tomcat-{{ tomcat_version }}"
        dest: "{{ tomcat_latest }}"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        state: link
      when: ansible_facts['os_family']=="Debian"
