---
- name: install javna on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: installing java
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present