---
- name: Install Lamp Stack
  become: yes
  hosts: all
  tasks:
     - name: update ubuntu packages
       apt:
         update_cache: yes
     - name: Install apache
       ansible.builtin.apt:
          name: apache2
          state: present
          update_cache: yes
       notify:
           Ensuring apache is enabled
     - name: Install PHP Package1
       ansible.builtin.apt:
           name: php
           state: present
       notify:
           Ensuring apache is enabled
     - name: Install PHP Package2
       ansible.builtin.apt:
           name: libapache2-mod-php
           state: present
       notify:
           Ensuring apache is enabled
     - name: Install PHP Package3
       ansible.builtin.apt:
           name: php-mysql
           state: present
       notify:
           Ensuring apache is enabled
     - name: copy the php info page
       ansible.builtin.copy:
           remote_src: www/info.php
           dest: /var/www/html/info.php
       notify:
           Ensuring apache is enabled   
  handlers:
       - name: Ensuring apache is enabled
         ansible.builtin.service:
            name: apache2
            enabled: yes
            state: restarted
        
      