---
- name: install java on both ubuntu and redhar
  hosts: appserver
  become: yes
  tasks:
    - name: install java on ubuntu and redhat
      ansible.builtin.package:
        name: "{{ java_package }}"
        state: present
